03/commerce/commerce/auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_listing", views.create_listing, name="create_listing"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("categories", views.categories_index, name="categories_index"),
    path("categories/<str:q>", views.categories, name="categories"),
    path("listing/<int:id>", views.listing, name="listing"),
    path("closed", views.closed, name="closed"),
]

03/commerce/commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

03/commerce/commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    bids = models.CharField(null=True, blank=True, max_length=128)

class Listing(models.Model):
    title = models.CharField(max_length=128)
    description = models.CharField(max_length=512)
    img_url = models.URLField(blank = True, max_length=256)
    create_date = models.DateTimeField ()
    start_bid = models.FloatField()
    best_bid = models.FloatField(null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner")
    best_bidder = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL, related_name="current_winner")
    watchlist = models.ManyToManyField(User, null=True, blank=True, related_name="watchlister")
    is_active = models.BooleanField()
    class Category(models.TextChoices):
        FAS = "1", "Fashion"
        TOY = "2", "Toys"
        ELE = "3", "Electronics"
        HOM = "4", "Home"
        GRO = "5", "Groceries"
        OTH = "6", "Others"

        def __str__(self):
            return f"{self.label}"
    
    category = models.CharField(
        max_length=2,
        choices=Category.choices,
    )

    def __str__ (self):
        return self.title

class Bid(models.Model):
    title = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="item_b")
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bidder")
    price = models.FloatField()
    bid_date = models.DateTimeField()
    
class Comment(models.Model):
    title = models.ForeignKey(Listing, on_delete=models.CASCADE, related_name="item_c")
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commenter")
    comment = models.CharField(max_length=512)
    comment_date = models.DateTimeField()

    def __str__(self):
        return f"{self.commenter}: {self.comment}"

03/commerce/commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from .models import User, Listing, Bid, Comment
import datetime
from django.db.models import Max, Q
from django.db.models.functions import Random


class ListingForm(forms.ModelForm):
    class Meta:
        model = Listing
        fields = '__all__'
        fields = ['title', 'description','category', 'start_bid', 'img_url']
        labels = {
            'title': '', 'description': '','category': '', 'start_bid': '', 'img_url': ''
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'm-2 rounded-5 form-control form-control-lg',
             'placeholder': 'Title', 'style': 'text-align: center;'}),
            'description': forms.Textarea(attrs={'class': 'm-2 rounded-5 form-control', 'rows': 10,
             'cols': 150, 'placeholder': 'Description', 'style': 'height: auto;'}),
             'category': forms.Select(attrs={'class': 'm-2 rounded-5 form-control'}),
            'start_bid': forms.NumberInput(attrs={'class': 'm-2 rounded-5 form-control', 'min': 0,
             'max': 100, 'placeholder': 'Bid start'}),
            'img_url': forms.URLInput(attrs={'class': 'm-2 rounded-5 form-control', 'placeholder': 'Iamge URL'}),
        }

class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ['price']
        labels = {
            'price': ''
        }
        widgets = {
            'price': forms.NumberInput(attrs={'class': 'mt-4 m-2 rounded-5 form-control',
             'min': 0, 'max': 100, 'Placeholder': 'Bid price'})
        }

    def __init__(self, *args, **kwargs):
        min_value = kwargs.pop('min_value', None)
        super().__init__(*args, **kwargs)
        if min_value is not None:
            self.fields['price'].widget.attrs['min'] = min_value

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']
        labels = {
            'comment': ''
        }
        widgets = {
            'comment': forms.Textarea(attrs={'class': 'm-2 rounded-5 form-control', 'rows': 5, 'cols': 50,
        'placeholder': 'Your Comment', 'style': 'height: auto;'})
        }

def index(request):
    # it should modify to active except all objects
    listings = Listing.objects.filter(is_active = True).order_by(Random())
    return render(request, "auctions/index.html", {
        "listings": listings
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")

def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


@login_required(login_url="/login")
def create_listing(request):
    if request.method == "POST":
        form = ListingForm(request.POST)
        if form.is_valid():
            listing = Listing()
            listing.title = form.cleaned_data["title"]
            listing.description = form.cleaned_data["description"]
            listing.start_bid = form.cleaned_data["start_bid"]
            listing.img_url = form.cleaned_data["img_url"]
            listing.is_active = True
            listing.category = form.cleaned_data["category"]
            listing.create_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            listing.owner = request.user
            listing.save()
            return HttpResponseRedirect(reverse("index"))
    form = ListingForm()
    return render(request, "auctions/new.html", {
        "form": form
    })

def listing(request, id):
    listing = Listing.objects.get(id = id)
    if request.method == "POST":
        print(request.POST)
        if "watchlist" in request.POST:
            if request.user in listing.watchlist.all():
                listing.watchlist.remove(request.user)
            else:
                listing.watchlist.add(request.user)
        elif "price" in request.POST:
            form_bid = BidForm(request.POST)
            if form_bid.is_valid():
                bid = Bid()
                bid.title = listing
                bid.bidder = request.user
                bid.bid_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                bid.price = form_bid.cleaned_data["price"]
                bid.save()
                listing.best_bid = bid.price
                listing.best_bidder = bid.bidder
                listing.save()
        elif "closing" in request.POST:
            listing.is_active = False
            listing.save()
            return HttpResponseRedirect(reverse("index"))
        else:
            form_comment = CommentForm(request.POST)
            if form_comment.is_valid():
                comment = Comment()
                comment.title = listing
                comment.commenter = request.user
                comment.comment_date = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                comment.comment = form_comment.cleaned_data["comment"]
                comment.save()

    """max_price_bid = Bid.objects.aggregate(Max('price'))
    max_price = max_price_bid['price__max']"""
    if listing.best_bid:
        min_value = 1.01 * listing.best_bid
    else:
        min_value = listing.start_bid
    form_bid = BidForm(min_value = min_value)
    form_comment = CommentForm()
    bids = Bid.objects.filter(title = listing.id)
    comments = Comment.objects.filter(title = listing.id)
    return render(request, "auctions/listing.html", {
        "listing": listing, "bids": bids, "comments": comments, "form_bid": form_bid,
        "form_comment":form_comment, "watchlist": request.user in listing.watchlist.all()
    })

@login_required(login_url="/login")
def watchlist(request):
    criterion1 = Q(watchlist = request.user)
    criterion2 = Q(is_active = True)
    listings = Listing.objects.filter(criterion1 & criterion2)
    return render(request, "auctions/index.html", {
        "listings": listings
    })

def categories_index(request):
    categories = Listing.Category.choices
    return render(request, "auctions/categories.html", {
        "categories": categories
    })

def categories(request, q):
    criterion1 = Q(category = q)
    criterion2 = Q(is_active = True)
    listings = Listing.objects.filter(criterion1 & criterion2)
    return render(request, "auctions/index.html", {
        "listings": listings
    })

def closed(request):
    listings = Listing.objects.filter(is_active = False)
    return render(request, "auctions/closed.html", {
        "listings": listings
    })

03/commerce/commerce/auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2><strong>Categories</strong></h2>
        <div class="ms-4 me-4">
            {% for category in categories %}
            <div class="p-3 rounded-5">
                    <a href="categories/{{ category.0 }}" class="nounderline">
                        <h3><strong>{{ category.1 }}</strong></h3>
                    </a>
            </div>

            {% empty %}
                <div class="d-flex justify-content-center text-danger">
                    <h3>There is no listing To Show!</h3>
                </div>
            {% endfor %}
        </div>
{% endblock %}

03/commerce/commerce/auctions/templates/auctions/closed.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2><strong>Active Listings</strong></h2>
        <div class="ms-4 me-4 flex-container">
            {% for listing in listings %}
            <div class="p-4 d-flex justify-content-center center-listings listing-s rounded-5">
                    <a href="listing/{{listing.id}}" class="nounderline">
                        <div class="text-dark nounderline">
                            <h2><strong>{{ listing.title }}</strong></h2>
                        </div>
                        <div class="text-dark nounderline">
                            Category: {{ listing.get_category_display }}
                        </div>
                        <div>
                            {% if listing.img_url %}
                                <img src="{{listing.img_url}}" alt="{{listing.title}}" class="img-index">
                            {% else %}
                                <img src="https://icon-library.com/images/no-picture-available-icon/no-picture-available-icon-1.jpg"
                                alt="{{listing.title}}" class="img-index">
                            {% endif %}
                        </div>
                        <div class="text-dark des_s">
                            {{listing.description}}
                        </div>
                        <div class="text-dark">
                            {% if request.user == listing.best_bidder %}
                                <h2><strong>YOU won the bid at {{listing.best_bid}}$ !</strong></h2>
                            {% else %}
                                {{listing.best_bidder}} won the bid at {{listing.best_bid}}$
                            {% endif %}
                        </div>    
                    </a>
            </div>

            {% empty %}
                <div class="d-flex justify-content-center text-danger">
                    <h3>There is no listing To Show!</h3>
                </div>
            {% endfor %}
        </div>
{% endblock %}

03/commerce/commerce/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2><strong>Active Listings</strong></h2>
        <div class="ms-5 me-5 flex-container">
            {% for listing in listings %}
            <div class="p-4 d-flex justify-content-center center-listings rounded-5">
                    <a href="listing/{{listing.id}}" class="nounderline">
                        <div class="text-dark nounderline">
                            <h2><strong>{{listing.title}}</strong></h2>
                        </div>
                        <div>
                            {% if listing.img_url %}
                                <img src="{{listing.img_url}}" alt="{{listing.title}}" class="img-index">
                            {% else %}
                                <img src="https://icon-library.com/images/no-picture-available-icon/no-picture-available-icon-1.jpg"
                                alt="{{listing.title}}" class="img-index">
                            {% endif %}
                        </div>
                        <div class="text-dark des_s">
                            {{listing.description}}
                        </div>
                        <div class="text-dark">
                            {% if listing.best_bid %}
                                <h2><strong>Current Bid Winner: {{listing.best_bid}}$</strong></h2>
                            {% else %}
                                <h3>Bid Starts: {{listing.start_bid}}$</h3>
                            {% endif %}
                        </div>    
                    </a>
            </div>

            {% empty %}
                <div class="d-flex justify-content-center text-danger">
                    <h3>There is no active listing!</h3>
                </div>
            {% endfor %}
        </div>
{% endblock %}

03/commerce/commerce/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'closed' %}">Closed</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'categories_index' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create_listing' %}">Create Listing</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

03/commerce/commerce/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2><strong>Bid</strong></h2>
        <div class="ms-4 me-4 flex-container">
            <div class="p-4 justify-content-center center-listings rounded-5">
                <div class="text-center">
                    <h2><strong>{{listing.title}}</strong></h2>
                </div>
                <div class="text-dark nounderline">
                    Category: {{ listing.get_category_display }}
                </div>
                <div>
                    <div class="image-container">
                        {% if listing.img_url %}
                            <img src="{{listing.img_url}}" alt="{{listing.title}}" class="img-index">
                        {% else %}
                            <img src="https://icon-library.com/images/no-picture-available-icon/no-picture-available-icon-1.jpg" alt="{{listing.title}}" class="img-index">
                        {% endif %}
                        {% if user.is_authenticated and request.user != listing.owner %}
                            <form action="{{listing.id}}" method="post">
                                {% csrf_token %}
                                {% if watchlist %}
                                    <input type="submit" class="watchlist-button-enabled" value="Watchlist" name="watchlist">
                                {% else %}
                                    <input type="submit" class="watchlist-button-disabled" value="Watchlist" name="watchlist">
                                {% endif %}
                            </form>
                        {% endif %}
                    </div>
                </div>
                <div class="text-dark des_s">
                    {{listing.description}}
                </div>
                <div class="text-dark text-center">
                    {% if listing.is_active %}
                        {% if listing.best_bid %}
                            <h2><strong>Current Bid Winner: {{listing.best_bid}}$</strong></h2>
                        {% else %}
                            <h3>Bid Starts: {{listing.start_bid}}$</h3>
                        {% endif %}
                    {% else %}
                        {% if request.user == listing.best_bidder %}
                            <h2><strong>YOU won the bid at {{listing.best_bid}}$ !</strong></h2>
                        {% else %}
                            {{listing.best_bidder}} won the bid at {{listing.best_bid}}$
                        {% endif %}
                    {% endif %}
                </div>
            </div>
            <div class="mt-4 p-2 justify-content-center center-listings rounded-5">
                {% if listing.is_active %}
                    {% if user.is_authenticated and request.user != listing.owner %}
                        <form action="{{listing.id}}" method="post" class="mt-4 listing-form" name="to_bid">
                            {% csrf_token %}
                            {{ form_bid }}
                            <input class="rounded-5 btn btn-primary" type="submit" value="Bid !">
                        </form>
                    {% endif %}
                    {% if request.user == listing.owner %}
                        <form action="{{listing.id}}" method="post" class="listing-form">
                            {% csrf_token %}
                            <input class="m-4 rounded-5 btn btn-danger" type="submit" value="Close the Bid !" name="closing">
                        </form>
                    {% endif %}
                {% else %}
                    <h3>Listing has been closed</h3>
                {% endif %}

                <div class="mt-4 p-2 rounded-5">
                    <h2>Details:</h2>
                    <strong>Listed By: {{ listing.owner }}</strong><br>
                    {% for bid in bids %}
                        at {{bid.bid_date}}, {{bid.bidder}} bided to {{bid.price}}$ price<br>
                    {% endfor %}
                </div>
            </div>
            <div class="mt-4 p-2 justify-content-center center-listings rounded-5">
                <div class="mt-4 text-center">
                    <h2><strong>Comments</strong></h2>
                </div> 
                <div des_s>
                    {% for comment in comments %}
                        {{ comment }}<br>
                    {% empty %}
                        No comments till now
                    {% endfor %}
                </div>
                <div class="m-2 p-2 rounded-5">
                    <h2>Write Your Comment:</h2>
                </div>
                {% if user.is_authenticated and request.user != listing.owner %}
                    <form action="{{listing.id}}" method="post" class="listing-form" name="commenting">
                        {% csrf_token %}
                        {{ form_comment }}
                        <input class="rounded-5 btn btn-primary" type="submit" value="Comment !">
                    </form>
                {% endif %}
            </div>
        </div>
{% endblock %}

03/commerce/commerce/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}
    <div class="m-5">
        <form action="{% url 'login' %}" method="post" class="center-form">
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-group">
                <input class="form-control" type="password" name="password" placeholder="Password">
            </div>
            <input class="btn btn-primary" type="submit" value="Login">
        </form>
    </div>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

03/commerce/commerce/auctions/templates/auctions/new.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Create Listing</h2>
    <div class="m-5">
        <form action="{% url 'create_listing' %}" method="post" class="center-form listing-s">
            {% csrf_token %}
            {{ form }}
            <input class="rounded-5 btn btn-primary" type="submit" value="Save!">
        </form>
    </div>
{% endblock %}

03/commerce/commerce/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post" class="center-form">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}